[package]
name = "stable_mir"
version = "0.1.0-preview"
edition = "2021"

[dependencies]
tracing = "0.1"
scoped-tls = "1.0"
serde = { version = "1.0.125", features = [ "derive" ] }
serde_json = { version = "1.0" }
rustc_data_structures = "0.0.0"